# example 1: on push to master
name: 自动tag
on:
  push:
    paths:
      - 'change.log'
  # schedule:
  #   - cron: '0 15 */3 * *'
env:
  TZ: 'Asia/Shanghai'
jobs:
  build:
    runs-on: ubuntu-22.04
    # permissions:
    #   contents: write
    #   packages: write
    steps:
      - name: Checkout Github Code
        uses: actions/checkout@v3

      - name: 生成环境变量
        run: |
          echo "GITHUB_MY_TAG=$(date +v%Y.%m.%d%H%M)" >> $GITHUB_ENV
      - name: 输出生成环境变量
        run: |
          echo ${{ env }}
      - name: Autotag
        uses: cardinalby/git-tag-action@master
        env:
          TAG: ${{ env.GITHUB_MY_TAG }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Golang
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          cache-dependency-path: '**/go.sum'
      - name: 准备环境
        run: |
          echo ${{ env.GITHUB_MY_TAG }}
          go install github.com/gogf/gf/cmd/gf/v2@latest
          gf build
      - name: show files
        run: |
          ls -la
          tree temp
      - name: Login
        uses: docker/login-action@v3
        with:
          registry: ccr.ccs.tencentyun.com
          username: ${{ secrets.DOCKER_NAME }}
          password: ${{ secrets.DOCKER_PWD }}
      - name: show files
        run: |
          docker build -t ccr.ccs.tencentyun.com/hailaz/gfqa:${{ env.GITHUB_MY_TAG }} -f ./manifest/docker/Dockerfile .
          docker push ccr.ccs.tencentyun.com/hailaz/gfqa:${{ env.GITHUB_MY_TAG }}
